inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - bin
    - gemfiles

Style/AndOr:
  EnforcedStyle: conditionals

Style/BlockDelimiters:
  EnforcedStyle: semantic
  IgnoredMethods:
    - before
    - each
    - it
    - let
    - new
    - watch
  FunctionalMethods:
    - trap

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/FormatString:
  EnforcedStyle: sprintf

# TODO - figure out if frozen string literals will be ok.
Style/FrozenStringLiteralComment:
  Enabled: false

# TODO - add docs to code.
Style/Documentation:
  Enabled: false
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'

# maybe eventually, if positional tokens become difficult to maintain.
Style/FormatStringToken:
  Enabled: false
