inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - bin
    - gemfiles

Style/AndOr:
  EnforcedStyle: conditionals

Style/BlockDelimiters:
  EnforcedStyle: semantic
  IgnoredMethods:
    - before
    - each
    - it
    - let
    - new
    - watch
  FunctionalMethods:
    - trap

# Maybe eventually, just not for now.
Style/Documentation:
  Enabled: false
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/FormatString:
  EnforcedStyle: sprintf

# maybe eventually.
Style/FormatStringToken:
  Enabled: false

# maybe eventually
Style/FrozenStringLiteralComment:
  Enabled: false
