inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - bin
    - gemfiles

Style/AndOr:
  EnforcedStyle: conditionals

Style/BlockDelimiters:
  EnforcedStyle: semantic
  IgnoredMethods:
    - before
    - each
    - it
    - let
    - new
    - watch
  FunctionalMethods:
    - trap
