language: ruby
bundler_args: --without development
cache: bundler
rvm:
  - "2.0"
  # - "2.1" # uses a bundler that has this bug: https://github.com/bundler/bundler/issues/3558
  - "2.2"
  - "2.3"
  - "2.4"
  - "2.5"
  - "2.6"
bundler_args: "--binstubs bin"
gemfile:
  - gemfiles/resque-min
  - gemfiles/resque-latest
